# coding: utf-8

"""
    Lumminary API

    A general-purpose API for accessing genomic data  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CustomerAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'city': 'str',
        'address1': 'str',
        'address2': 'str',
        'zipcode': 'str',
        'phone': 'str',
        'state': 'str',
        'country': 'str'
    }

    attribute_map = {
        'city': 'city',
        'address1': 'address1',
        'address2': 'address2',
        'zipcode': 'zipcode',
        'phone': 'phone',
        'state': 'state',
        'country': 'country'
    }

    def __init__(self, city=None, address1=None, address2=None, zipcode=None, phone=None, state=None, country=None):  # noqa: E501
        """CustomerAddress - a model defined in Swagger"""  # noqa: E501

        self._city = None
        self._address1 = None
        self._address2 = None
        self._zipcode = None
        self._phone = None
        self._state = None
        self._country = None
        self.discriminator = None

        self.city = city
        self.address1 = address1
        if address2 is not None:
            self.address2 = address2
        self.zipcode = zipcode
        self.phone = phone
        if state is not None:
            self.state = state
        self.country = country

    @property
    def city(self):
        """Gets the city of this CustomerAddress.  # noqa: E501

          # noqa: E501

        :return: The city of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this CustomerAddress.

          # noqa: E501

        :param city: The city of this CustomerAddress.  # noqa: E501
        :type: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city

    @property
    def address1(self):
        """Gets the address1 of this CustomerAddress.  # noqa: E501

          # noqa: E501

        :return: The address1 of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._address1

    @address1.setter
    def address1(self, address1):
        """Sets the address1 of this CustomerAddress.

          # noqa: E501

        :param address1: The address1 of this CustomerAddress.  # noqa: E501
        :type: str
        """
        if address1 is None:
            raise ValueError("Invalid value for `address1`, must not be `None`")  # noqa: E501

        self._address1 = address1

    @property
    def address2(self):
        """Gets the address2 of this CustomerAddress.  # noqa: E501

          # noqa: E501

        :return: The address2 of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._address2

    @address2.setter
    def address2(self, address2):
        """Sets the address2 of this CustomerAddress.

          # noqa: E501

        :param address2: The address2 of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._address2 = address2

    @property
    def zipcode(self):
        """Gets the zipcode of this CustomerAddress.  # noqa: E501

          # noqa: E501

        :return: The zipcode of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._zipcode

    @zipcode.setter
    def zipcode(self, zipcode):
        """Sets the zipcode of this CustomerAddress.

          # noqa: E501

        :param zipcode: The zipcode of this CustomerAddress.  # noqa: E501
        :type: str
        """
        if zipcode is None:
            raise ValueError("Invalid value for `zipcode`, must not be `None`")  # noqa: E501

        self._zipcode = zipcode

    @property
    def phone(self):
        """Gets the phone of this CustomerAddress.  # noqa: E501

          # noqa: E501

        :return: The phone of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this CustomerAddress.

          # noqa: E501

        :param phone: The phone of this CustomerAddress.  # noqa: E501
        :type: str
        """
        if phone is None:
            raise ValueError("Invalid value for `phone`, must not be `None`")  # noqa: E501

        self._phone = phone

    @property
    def state(self):
        """Gets the state of this CustomerAddress.  # noqa: E501

          # noqa: E501

        :return: The state of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this CustomerAddress.

          # noqa: E501

        :param state: The state of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def country(self):
        """Gets the country of this CustomerAddress.  # noqa: E501

          # noqa: E501

        :return: The country of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this CustomerAddress.

          # noqa: E501

        :param country: The country of this CustomerAddress.  # noqa: E501
        :type: str
        """
        if country is None:
            raise ValueError("Invalid value for `country`, must not be `None`")  # noqa: E501

        self._country = country

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomerAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
