# coding: utf-8

"""
    Lumminary API

    A general-purpose API for accessing genomic data  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FileLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'str',
        'host': 'str',
        'filename_original': 'str'
    }

    attribute_map = {
        'path': 'path',
        'host': 'host',
        'filename_original': 'filename_original'
    }

    def __init__(self, path=None, host=None, filename_original=None):  # noqa: E501
        """FileLocation - a model defined in Swagger"""  # noqa: E501

        self._path = None
        self._host = None
        self._filename_original = None
        self.discriminator = None

        self.path = path
        self.host = host
        self.filename_original = filename_original

    @property
    def path(self):
        """Gets the path of this FileLocation.  # noqa: E501


        :return: The path of this FileLocation.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this FileLocation.


        :param path: The path of this FileLocation.  # noqa: E501
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def host(self):
        """Gets the host of this FileLocation.  # noqa: E501


        :return: The host of this FileLocation.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this FileLocation.


        :param host: The host of this FileLocation.  # noqa: E501
        :type: str
        """
        if host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501

        self._host = host

    @property
    def filename_original(self):
        """Gets the filename_original of this FileLocation.  # noqa: E501


        :return: The filename_original of this FileLocation.  # noqa: E501
        :rtype: str
        """
        return self._filename_original

    @filename_original.setter
    def filename_original(self, filename_original):
        """Sets the filename_original of this FileLocation.


        :param filename_original: The filename_original of this FileLocation.  # noqa: E501
        :type: str
        """
        if filename_original is None:
            raise ValueError("Invalid value for `filename_original`, must not be `None`")  # noqa: E501

        self._filename_original = filename_original

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
