# coding: utf-8

"""
    Lumminary API

    A general-purpose API for accessing genomic data  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MolecularLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'int',
        'stop': 'int',
        'chromosome_accession': 'str'
    }

    attribute_map = {
        'start': 'start',
        'stop': 'stop',
        'chromosome_accession': 'chromosome_accession'
    }

    def __init__(self, start=None, stop=None, chromosome_accession=None):  # noqa: E501
        """MolecularLocation - a model defined in Swagger"""  # noqa: E501

        self._start = None
        self._stop = None
        self._chromosome_accession = None
        self.discriminator = None

        self.start = start
        self.stop = stop
        self.chromosome_accession = chromosome_accession

    @property
    def start(self):
        """Gets the start of this MolecularLocation.  # noqa: E501

        The gene's start position on the scaffold  # noqa: E501

        :return: The start of this MolecularLocation.  # noqa: E501
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this MolecularLocation.

        The gene's start position on the scaffold  # noqa: E501

        :param start: The start of this MolecularLocation.  # noqa: E501
        :type: int
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501
        if start is not None and start < 0:  # noqa: E501
            raise ValueError("Invalid value for `start`, must be a value greater than or equal to `0`")  # noqa: E501

        self._start = start

    @property
    def stop(self):
        """Gets the stop of this MolecularLocation.  # noqa: E501

        The gene's stop position on the scaffold  # noqa: E501

        :return: The stop of this MolecularLocation.  # noqa: E501
        :rtype: int
        """
        return self._stop

    @stop.setter
    def stop(self, stop):
        """Sets the stop of this MolecularLocation.

        The gene's stop position on the scaffold  # noqa: E501

        :param stop: The stop of this MolecularLocation.  # noqa: E501
        :type: int
        """
        if stop is None:
            raise ValueError("Invalid value for `stop`, must not be `None`")  # noqa: E501
        if stop is not None and stop < 0:  # noqa: E501
            raise ValueError("Invalid value for `stop`, must be a value greater than or equal to `0`")  # noqa: E501

        self._stop = stop

    @property
    def chromosome_accession(self):
        """Gets the chromosome_accession of this MolecularLocation.  # noqa: E501

        The cromosome on which the gene is placed  # noqa: E501

        :return: The chromosome_accession of this MolecularLocation.  # noqa: E501
        :rtype: str
        """
        return self._chromosome_accession

    @chromosome_accession.setter
    def chromosome_accession(self, chromosome_accession):
        """Sets the chromosome_accession of this MolecularLocation.

        The cromosome on which the gene is placed  # noqa: E501

        :param chromosome_accession: The chromosome_accession of this MolecularLocation.  # noqa: E501
        :type: str
        """
        if chromosome_accession is None:
            raise ValueError("Invalid value for `chromosome_accession`, must not be `None`")  # noqa: E501
        if chromosome_accession is not None and len(chromosome_accession) < 1:
            raise ValueError("Invalid value for `chromosome_accession`, length must be greater than or equal to `1`")  # noqa: E501

        self._chromosome_accession = chromosome_accession

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MolecularLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
