# coding: utf-8

"""
    Lumminary API

    A general-purpose API for accessing genomic data  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PublicSNP(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reference_allele': 'str',
        'reference_genome': 'str',
        'dbsnp_version': 'int',
        'chromosome_accession': 'str',
        'snp_id': 'str',
        'alternative_alleles': 'list[str]',
        'chromosome': 'str',
        'location': 'int'
    }

    attribute_map = {
        'reference_allele': 'reference_allele',
        'reference_genome': 'reference_genome',
        'dbsnp_version': 'dbsnp_version',
        'chromosome_accession': 'chromosome_accession',
        'snp_id': 'snp_id',
        'alternative_alleles': 'alternative_alleles',
        'chromosome': 'chromosome',
        'location': 'location'
    }

    def __init__(self, reference_allele=None, reference_genome=None, dbsnp_version=None, chromosome_accession=None, snp_id=None, alternative_alleles=None, chromosome=None, location=None):  # noqa: E501
        """PublicSNP - a model defined in Swagger"""  # noqa: E501

        self._reference_allele = None
        self._reference_genome = None
        self._dbsnp_version = None
        self._chromosome_accession = None
        self._snp_id = None
        self._alternative_alleles = None
        self._chromosome = None
        self._location = None
        self.discriminator = None

        self.reference_allele = reference_allele
        self.reference_genome = reference_genome
        self.dbsnp_version = dbsnp_version
        self.chromosome_accession = chromosome_accession
        self.snp_id = snp_id
        if alternative_alleles is not None:
            self.alternative_alleles = alternative_alleles
        self.chromosome = chromosome
        self.location = location

    @property
    def reference_allele(self):
        """Gets the reference_allele of this PublicSNP.  # noqa: E501

        One of the possible alleles  # noqa: E501

        :return: The reference_allele of this PublicSNP.  # noqa: E501
        :rtype: str
        """
        return self._reference_allele

    @reference_allele.setter
    def reference_allele(self, reference_allele):
        """Sets the reference_allele of this PublicSNP.

        One of the possible alleles  # noqa: E501

        :param reference_allele: The reference_allele of this PublicSNP.  # noqa: E501
        :type: str
        """
        if reference_allele is None:
            raise ValueError("Invalid value for `reference_allele`, must not be `None`")  # noqa: E501
        if reference_allele is not None and len(reference_allele) < 1:
            raise ValueError("Invalid value for `reference_allele`, length must be greater than or equal to `1`")  # noqa: E501

        self._reference_allele = reference_allele

    @property
    def reference_genome(self):
        """Gets the reference_genome of this PublicSNP.  # noqa: E501

        The ID and build number of the genome against which the SNP was built and placed  # noqa: E501

        :return: The reference_genome of this PublicSNP.  # noqa: E501
        :rtype: str
        """
        return self._reference_genome

    @reference_genome.setter
    def reference_genome(self, reference_genome):
        """Sets the reference_genome of this PublicSNP.

        The ID and build number of the genome against which the SNP was built and placed  # noqa: E501

        :param reference_genome: The reference_genome of this PublicSNP.  # noqa: E501
        :type: str
        """
        if reference_genome is None:
            raise ValueError("Invalid value for `reference_genome`, must not be `None`")  # noqa: E501
        if reference_genome is not None and len(reference_genome) < 1:
            raise ValueError("Invalid value for `reference_genome`, length must be greater than or equal to `1`")  # noqa: E501

        self._reference_genome = reference_genome

    @property
    def dbsnp_version(self):
        """Gets the dbsnp_version of this PublicSNP.  # noqa: E501

        The dbSNP build to which snip attributes like location and chromosome accession refer.  # noqa: E501

        :return: The dbsnp_version of this PublicSNP.  # noqa: E501
        :rtype: int
        """
        return self._dbsnp_version

    @dbsnp_version.setter
    def dbsnp_version(self, dbsnp_version):
        """Sets the dbsnp_version of this PublicSNP.

        The dbSNP build to which snip attributes like location and chromosome accession refer.  # noqa: E501

        :param dbsnp_version: The dbsnp_version of this PublicSNP.  # noqa: E501
        :type: int
        """
        if dbsnp_version is None:
            raise ValueError("Invalid value for `dbsnp_version`, must not be `None`")  # noqa: E501

        self._dbsnp_version = dbsnp_version

    @property
    def chromosome_accession(self):
        """Gets the chromosome_accession of this PublicSNP.  # noqa: E501

        The accession of the chromosome on which the SNP is placed  # noqa: E501

        :return: The chromosome_accession of this PublicSNP.  # noqa: E501
        :rtype: str
        """
        return self._chromosome_accession

    @chromosome_accession.setter
    def chromosome_accession(self, chromosome_accession):
        """Sets the chromosome_accession of this PublicSNP.

        The accession of the chromosome on which the SNP is placed  # noqa: E501

        :param chromosome_accession: The chromosome_accession of this PublicSNP.  # noqa: E501
        :type: str
        """
        if chromosome_accession is None:
            raise ValueError("Invalid value for `chromosome_accession`, must not be `None`")  # noqa: E501
        if chromosome_accession is not None and len(chromosome_accession) < 1:
            raise ValueError("Invalid value for `chromosome_accession`, length must be greater than or equal to `1`")  # noqa: E501

        self._chromosome_accession = chromosome_accession

    @property
    def snp_id(self):
        """Gets the snp_id of this PublicSNP.  # noqa: E501

        The ID of the SNP  # noqa: E501

        :return: The snp_id of this PublicSNP.  # noqa: E501
        :rtype: str
        """
        return self._snp_id

    @snp_id.setter
    def snp_id(self, snp_id):
        """Sets the snp_id of this PublicSNP.

        The ID of the SNP  # noqa: E501

        :param snp_id: The snp_id of this PublicSNP.  # noqa: E501
        :type: str
        """
        if snp_id is None:
            raise ValueError("Invalid value for `snp_id`, must not be `None`")  # noqa: E501
        if snp_id is not None and len(snp_id) < 1:
            raise ValueError("Invalid value for `snp_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._snp_id = snp_id

    @property
    def alternative_alleles(self):
        """Gets the alternative_alleles of this PublicSNP.  # noqa: E501


        :return: The alternative_alleles of this PublicSNP.  # noqa: E501
        :rtype: list[str]
        """
        return self._alternative_alleles

    @alternative_alleles.setter
    def alternative_alleles(self, alternative_alleles):
        """Sets the alternative_alleles of this PublicSNP.


        :param alternative_alleles: The alternative_alleles of this PublicSNP.  # noqa: E501
        :type: list[str]
        """

        self._alternative_alleles = alternative_alleles

    @property
    def chromosome(self):
        """Gets the chromosome of this PublicSNP.  # noqa: E501

        The cromosome on which the SNP is placed  # noqa: E501

        :return: The chromosome of this PublicSNP.  # noqa: E501
        :rtype: str
        """
        return self._chromosome

    @chromosome.setter
    def chromosome(self, chromosome):
        """Sets the chromosome of this PublicSNP.

        The cromosome on which the SNP is placed  # noqa: E501

        :param chromosome: The chromosome of this PublicSNP.  # noqa: E501
        :type: str
        """
        if chromosome is None:
            raise ValueError("Invalid value for `chromosome`, must not be `None`")  # noqa: E501
        if chromosome is not None and len(chromosome) < 1:
            raise ValueError("Invalid value for `chromosome`, length must be greater than or equal to `1`")  # noqa: E501

        self._chromosome = chromosome

    @property
    def location(self):
        """Gets the location of this PublicSNP.  # noqa: E501

        The SNP's position on the chromosome  # noqa: E501

        :return: The location of this PublicSNP.  # noqa: E501
        :rtype: int
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this PublicSNP.

        The SNP's position on the chromosome  # noqa: E501

        :param location: The location of this PublicSNP.  # noqa: E501
        :type: int
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501
        if location is not None and location < 0:  # noqa: E501
            raise ValueError("Invalid value for `location`, must be a value greater than or equal to `0`")  # noqa: E501

        self._location = location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PublicSNP):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
