# coding: utf-8

"""
    Lumminary API

    A general-purpose API for accessing genomic data  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ReportCredentials(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'report_credentials_uuid': 'str',
        'client_username': 'str',
        'authorization_uuid': 'str',
        'report_url': 'str',
        'create_timestamp': 'int',
        'client_password': 'str'
    }

    attribute_map = {
        'report_credentials_uuid': 'report_credentials_uuid',
        'client_username': 'client_username',
        'authorization_uuid': 'authorization_uuid',
        'report_url': 'report_url',
        'create_timestamp': 'create_timestamp',
        'client_password': 'client_password'
    }

    def __init__(self, report_credentials_uuid=None, client_username=None, authorization_uuid=None, report_url=None, create_timestamp=None, client_password=None):  # noqa: E501
        """ReportCredentials - a model defined in Swagger"""  # noqa: E501

        self._report_credentials_uuid = None
        self._client_username = None
        self._authorization_uuid = None
        self._report_url = None
        self._create_timestamp = None
        self._client_password = None
        self.discriminator = None

        self.report_credentials_uuid = report_credentials_uuid
        if client_username is not None:
            self.client_username = client_username
        self.authorization_uuid = authorization_uuid
        if report_url is not None:
            self.report_url = report_url
        self.create_timestamp = create_timestamp
        if client_password is not None:
            self.client_password = client_password

    @property
    def report_credentials_uuid(self):
        """Gets the report_credentials_uuid of this ReportCredentials.  # noqa: E501

        The uuid of the report  # noqa: E501

        :return: The report_credentials_uuid of this ReportCredentials.  # noqa: E501
        :rtype: str
        """
        return self._report_credentials_uuid

    @report_credentials_uuid.setter
    def report_credentials_uuid(self, report_credentials_uuid):
        """Sets the report_credentials_uuid of this ReportCredentials.

        The uuid of the report  # noqa: E501

        :param report_credentials_uuid: The report_credentials_uuid of this ReportCredentials.  # noqa: E501
        :type: str
        """
        if report_credentials_uuid is None:
            raise ValueError("Invalid value for `report_credentials_uuid`, must not be `None`")  # noqa: E501

        self._report_credentials_uuid = report_credentials_uuid

    @property
    def client_username(self):
        """Gets the client_username of this ReportCredentials.  # noqa: E501

        The generated username, on the partner product website  # noqa: E501

        :return: The client_username of this ReportCredentials.  # noqa: E501
        :rtype: str
        """
        return self._client_username

    @client_username.setter
    def client_username(self, client_username):
        """Sets the client_username of this ReportCredentials.

        The generated username, on the partner product website  # noqa: E501

        :param client_username: The client_username of this ReportCredentials.  # noqa: E501
        :type: str
        """

        self._client_username = client_username

    @property
    def authorization_uuid(self):
        """Gets the authorization_uuid of this ReportCredentials.  # noqa: E501

        The uuid of the authorization that generated this report  # noqa: E501

        :return: The authorization_uuid of this ReportCredentials.  # noqa: E501
        :rtype: str
        """
        return self._authorization_uuid

    @authorization_uuid.setter
    def authorization_uuid(self, authorization_uuid):
        """Sets the authorization_uuid of this ReportCredentials.

        The uuid of the authorization that generated this report  # noqa: E501

        :param authorization_uuid: The authorization_uuid of this ReportCredentials.  # noqa: E501
        :type: str
        """
        if authorization_uuid is None:
            raise ValueError("Invalid value for `authorization_uuid`, must not be `None`")  # noqa: E501

        self._authorization_uuid = authorization_uuid

    @property
    def report_url(self):
        """Gets the report_url of this ReportCredentials.  # noqa: E501

        URL to the report location  # noqa: E501

        :return: The report_url of this ReportCredentials.  # noqa: E501
        :rtype: str
        """
        return self._report_url

    @report_url.setter
    def report_url(self, report_url):
        """Sets the report_url of this ReportCredentials.

        URL to the report location  # noqa: E501

        :param report_url: The report_url of this ReportCredentials.  # noqa: E501
        :type: str
        """

        self._report_url = report_url

    @property
    def create_timestamp(self):
        """Gets the create_timestamp of this ReportCredentials.  # noqa: E501

        Creation timestamp for Report  # noqa: E501

        :return: The create_timestamp of this ReportCredentials.  # noqa: E501
        :rtype: int
        """
        return self._create_timestamp

    @create_timestamp.setter
    def create_timestamp(self, create_timestamp):
        """Sets the create_timestamp of this ReportCredentials.

        Creation timestamp for Report  # noqa: E501

        :param create_timestamp: The create_timestamp of this ReportCredentials.  # noqa: E501
        :type: int
        """
        if create_timestamp is None:
            raise ValueError("Invalid value for `create_timestamp`, must not be `None`")  # noqa: E501

        self._create_timestamp = create_timestamp

    @property
    def client_password(self):
        """Gets the client_password of this ReportCredentials.  # noqa: E501

        The password generated password, on the partner product website  # noqa: E501

        :return: The client_password of this ReportCredentials.  # noqa: E501
        :rtype: str
        """
        return self._client_password

    @client_password.setter
    def client_password(self, client_password):
        """Sets the client_password of this ReportCredentials.

        The password generated password, on the partner product website  # noqa: E501

        :param client_password: The client_password of this ReportCredentials.  # noqa: E501
        :type: str
        """

        self._client_password = client_password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportCredentials):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
