# coding: utf-8

"""
    Lumminary API

    A general-purpose API for accessing genomic data  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "lumminary_sdk"
VERSION = "1.0.7"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "pycryptodome >= 3.0.0", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Lumminary API",
    author_email="",
    url="",
    keywords=["Swagger", "Lumminary API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    A general-purpose API for accessing genomic data  # noqa: E501
    """
)
